### ISSUE TITLE
bug: Argmin and Argmax not working with 1D tensor

### ISSUE THREAD

**Issue by raphaelDkhn** [gizatechxyz/orion#107]
# Bug Report

**Current behavior:**
Currently Argmin and Argmax panics with 1D tensor. 
```
    let tensor = i32_tensor_1x3_helper();

    let result = tensor.argmin(0,Option::None(()),Option::None(()));

>>>> panicked with [('shape cannot be empty') ]
```

**Comment by credence0x** [comment]
[: fix for argmin with 1d tensor](https://github.com/credence0x/orion/commit/f4669b80fab1587fb32dd2d4c26a137b5cc09284)
@raphaelDkhn This was the best I could come up with. It's either this or we make a separate function to handle 1D tensors OR we have the rethink the entire argmin and argmax functions because there are many places we assume that the input tensor would have at least 2 dims (especially `combine_indices` helper function)

**Comment by raphaelDkhn** [comment]
Thanks @credence0x, yes I thought about smthg similar. But it adds unnecessary steps. 
So either we refactor `combine_indices` function. 
Or we handle the case of a 1D tensor. Look at what I've done for reduce_sum:
https://github.com/gizatechxyz/orion/blob/b47212fd4692915f5f6a9c850ac703ef6f5e4152/src/operators/tensor/math/reduce_sum/reduce_sum_u32.cairo#L15

**Comment by credence0x** [comment]
Hmmm. Yeah we can refactor `combine_indices` to make it work. But we can alse make the function a lot more gas efficient for 1D tensors if we just handle it separately (like reduce sum). I think that'll be better. Need your stamp of approval

**Comment by raphaelDkhn** [comment]
Yes I agree. Let's make the function more gas efficient by handling 1D tensors separately
